spring:
  application:
    name: paynest

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
